app/student/forms.py
from flask_wtf import FlaskForm as Form
from wtforms import RadioField, SubmitField
from wtforms.validators import DataRequired

class QuizQuestion(Form):
    pass

app/student/__init__.py
from flask import Blueprint

student = Blueprint('student', __name__)

from . import student, views, forms

app/student/views.py
from . import student
from app import db
from app.models import User, Quiz, Registrations, Question, StudentSolutions
from flask import render_template, url_for, session, redirect, flash, request
from flask_login import current_user,  login_required

# Render Student Home
@student.route('/studenthome')
@login_required
def studenthome():
    
    students_quizes = Registrations.query.filter_by(user_id=current_user.id).all()
    
    quizes_ids = [i.quiz_id for i in students_quizes]
    
    quizes = [q for q in Quiz.query.all() if q.id in quizes_ids]
    
    return render_template('student/studenthome.html', quizes=quizes)


# Get a specific quiz and its questions and return the questions in 
# a pagination object
@student.route('/getquiz/<int:id>/<int:qn_id>')
@login_required
def getquiz(id, qn_id):
    pagination = Question.query.filter_by(quiz_id=id).paginate(page=qn_id, per_page=1, error_out=False)
    quiz = Quiz.query.filter_by(id=id).first()
    
    if 'quiz_id' in session:
        session['quiz_id'] = id
        session.modified = True
    else:
        session['quiz_id'] = id
        
    quiz_name = quiz.name
    return render_template('student/takequiz.html', pagination=pagination, quiz_name=quiz_name)

# Submit a student's solution to a specific question
# on a specific quiz
@student.route('/addsolution/<int:qn_id>', methods=['POST', 'GET'])
@login_required
def addsolution(qn_id):
    if request.method == 'POST':
        quiz_id = session.get('quiz_id')
        student_solution = request.form.get('option')
        
        
        question = Question.query.filter_by(id=qn_id).first()
        correct_ans = question.correct_option
        
        # Check if solution is correct and set 
        # boolean to a variable to be sent to db
        iscorrect = None
        if student_solution == correct_ans:
            iscorrect = True
        else:
            iscorrect = False
        
        solution = StudentSolutions(user_id=current_user.id, question_id=qn_id, solution=student_solution, correct=iscorrect)
        
        try:
            db.session.add(solution)
            db.session.commit()
            flash('Done')
        except Exception as e:
            print('{}'.format(str(e)))    
            db.session.rollback()
    
    return redirect(url_for('student.getquiz', id=quiz_id, qn_id=qn_id))

app/templates/student/studenthome.html
{% extends "base.html" %}

{% block title %} Quizer - Register {% endblock %} 

{% block head %}
    {{ super() }}
{% endblock %}



{% block navbar %}
    {{ super() }}
{% endblock %}


<div class="container">
    {% block content %}
        {{ super() }}
        <div class="row">
            
            <div class="col">
                <h2 class="page-header text-light">Up Coming Quizes</h2>
                <table class="table" style="background-color: #343a40; color: #fff;">
                    {% for quiz in quizes %}
                        <tr style="border-bottom: 1px solid #262c33;" class="d-flex flex-row justify-content-between align-items-center">
                            <td style="border: none; color: #fff;">{{ quiz.name }}</td>
                            <td style="border: none; color: #fff;">
                               {{ moment(quiz.date).format('LL') }}
                            </td>
                            <td style="border: none; color: #fff;">
                                
                                <form action="{{ url_for('student.getquiz', id=quiz.id, qn_id=1) }}" method="get">
                                    <button type="submit" class="btn btn-outline-light">
                                        START
                                    </button>
                                </form>
                            </td>
                        </tr>
                    {% endfor %}
                </table>
            </div>
            <div class="col"></div>
        </div>
    {% endblock %}
</div>

app/templates/student/takequiz.html
{% extends "base.html" %}

{% block title %} Quizer - Register {% endblock %} 

{% block head %}
    {{ super() }}
{% endblock %}



{% block navbar %}
    {{ super() }}
{% endblock %}

<div class="container">
    {% block content %}
        {{ super() }}
        <div class="row d-flex align-items-center justify-content-center">
            {% for message in get_flashed_messages() %}
                <div class="alert alert-warning show fade" role="alert">
                    {{ message }}
                </div>
            {% endfor %}
            <div class="card w-50 text-white mb-3" style="background-color: #41484e;">
                <div class="card-header">
                    <h3 class="text-center">{{ quiz_name}}</h3>
                </div>
                <div class="card-body d-flex flex-column">
                    {% for item in pagination.items %}
                    <h4 class="card-title text-center">{{ item.detail }}</h4>
                    <form class="mt-3 mb-3" 
                            action="{{ url_for('student.addsolution', qn_id=item.id) }}" method="POST">
                        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                        <div class="form-check">
                            <input class="form-check-input" type="radio" name="option" id="exampleRadios1" value="{{ item.option1 }}">
                            <label class="form-check-label card-text" for="exampleRadios1">
                            {{ item.option1 }}
                            </label>
                        </div>
                        <div class="form-check">
                            <input class="form-check-input" type="radio" name="option" id="exampleRadios2" value="{{ item.option2 }}">
                            <label class="form-check-label" for="exampleRadios2">
                            {{ item.option2 }}
                            </label>
                        </div>
                        <div class="form-check">
                            <input class="form-check-input" type="radio" name="option" id="exampleRadios3" value="{{ item.option3 }}">
                            <label class="form-check-label" for="exampleRadios3">
                            {{ item.option3 }}
                            </label>
                        </div>
                        <div class="form-check">
                            <input class="form-check-input" type="radio" name="option" id="exampleRadios4" value="{{ item.option4 }}">
                            <label class="form-check-label" for="exampleRadios4">
                            {{ item.option4 }}
                            </label>
                        </div>
                        <div class="form-group mt-2">
                            <button class="btn btn-danger w-100" type="submit">Submit Solution</button>
                        </div>
                    </form>
                    {% if not pagination.has_next %}
                        <button class="btn btn-outline-light w-100" disabled type="submit">Next</button>
                    {% else %}
                        <form action="{{ url_for('student.getquiz', id=item.quiz_id, qn_id=pagination.next_num) }}" method="get">
                            <button class="btn btn-outline-light w-100" type="submit">Next</button>
                        </form>
                    {% endif %}
                    {% endfor %}
                </div>
                <div class="card-footer text-muted text-center">
                  2 days ago
                </div>
              </div>
        </div>
    {% endblock %}
</div>