app/examiner/forms.py
from flask_wtf import Form
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired, AnyOf

class QuestionForm(Form):
    detail = StringField('Question', validators=[DataRequired()])
    option1 = StringField('Option 1', validators=[DataRequired()])
    option2 = StringField('Option 2', validators=[DataRequired()])
    option3 = StringField('Option 3', validators=[DataRequired()])
    option4 = StringField('Option 4', validators=[DataRequired()])
    correct_option = StringField('Solution', validators=[DataRequired()])
    submit = SubmitField('Add')

app/examiner/__init__.py
''' Examiner blueprint '''
from flask import Blueprint

examiner = Blueprint('examiner', __name__)

from . import views

app/examiner/views.py
''' Routes and View Functions for The Examiner user's functionalities'''
from app import db
from app.models import Quiz, Question, User, Registrations
from datetime import date, time
from flask import flash, render_template, url_for, redirect, request, jsonify
from flask_login import login_required, current_user
from . import examiner
from .forms import QuestionForm

# Home page
@examiner.route('/examinerhome')
def examinerhome():
    return render_template('examiner/examiner_home.html')

# Render quiz list
@examiner.route('/quizlist')
@login_required
def quizlist():
    quizes = Quiz.query.filter_by(user_id=current_user.id).all()
    return render_template('examiner/quizlist.html', quizes=quizes)


# specific quiz
@examiner.route('/onequiz/<int:id>/<int:qid>')
@login_required
def onequiz(id, qid):
    form = QuestionForm()
    page = request.args.get('qid')
    quiz = Quiz.query.filter_by(id=id, user_id=current_user.id).first()
    
    pagination = Question.query.paginate(page=qid, per_page=1, error_out=False)
    
    student_users = User.query.filter_by(role='STUDENT').all()  # all students
    
    reg_students = Registrations.query.filter_by(quiz_id=id).all()   # list of students registered for this quiz
    
    registered = [r.user_id for r in reg_students]  # list of registered student's user id's
    
    students = filter(lambda s: s.id not in registered, student_users)  # filter out the students not registered

    return render_template('examiner/quiz_n.html', form=form, pagination=pagination, 
                           quiz=quiz, students=list(students))

# Add new quiz
@examiner.route('/addquiz', methods=['POST', 'GET'])
@login_required
def addquiz():
    if current_user.role != 'EXAMINER':
        return
    if request.method == 'POST':
        quiz_name = request.form['quizname']
        quiz_day = request.form['quizdate'].split('-')
        quiz_time = request.form['quiztime'].split(':')
        
        
        day = date(int(quiz_day[0]), int(quiz_day[1]), int(quiz_day[2]))
        tim = time(int(quiz_time[0]), int(quiz_time[1]))
        
        try:
            quiz = Quiz(name=quiz_name, date=day, time=tim, user_id=current_user.id)
            
            db.session.add(quiz)
            db.session.commit()
            flash("Success")
        except Exception as e:
            flash("{}".format(str(e)))        
            db.session.rollback()
    return redirect(url_for('examiner.examinerhome'))

@examiner.route('/addquestion/<int:quiz_id>', methods=['GET', 'POST'])
@login_required
def addquestion(quiz_id):
    form = QuestionForm()
    if form.validate_on_submit():
        question = Question()
        
        question.detail = form.detail.data
        question.option1 = form.option1.data
        question.option2 = form.option2.data
        question.option3 = form.option3.data
        question.option4 = form.option4.data
        question.correct_option = form.correct_option.data
        question.quiz_id = quiz_id
        
        try:
            db.session.add(question)
            db.session.commit()
            flash("Success")
        except Exception as e:
            flash('{}'.form(str(e)))
    else:
        flash(form.errors['correct_option'])
    
    return redirect(url_for('examiner.onequiz', id=quiz_id, qid=1))


@examiner.route('/registerstudents/<int:id>', methods=['POST', 'GET'])
@login_required
def registerstudents(id):
    
    student_dets = request.form.getlist('student')  # add all students selected to be added to table
    
    students = []
    
    for s in student_dets:
        registration = Registrations()
        
        registration.user_id = int(s)
        registration.quiz_id = id
        
        students.append(registration)
    
    try:
        db.session.add_all(students)
        db.session.commit()
        print('success')
    except Exception as e:
        print(str(e))
    return redirect(url_for('examiner.onequiz', id=id, qid=1))
    
    


    

app/templates/examiner/examiner_home.html
{% extends "base.html" %}

{% block title %} Quizer - Register {% endblock %} 

{% block head %}
    {{ super() }}
{% endblock %}



{% block navbar %}
    <div class="container">
        {{ super() }}
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a href="#" class="nav-link">Home</a>
                </li>
                <li class="nav-item">
                    <a href="{{ url_for('examiner.quizlist') }}" class="nav-link">Quizes</a>
                </li>
            </ul>
        </div>
    </div>
{% endblock %}

{% block content %}
    {{ super() }}
    <div class="row text-light">
        <div class="col">
            <div class="card" style="background-color: inherit; color: inherit;">
                <h5 class="card-header">Profile</h5>
                <div class="card-body">
                    <h6 class="card-text"> {{ current_user.fname }} {{ current_user.lname }} </h6>
                    <hr>
                    <h6 class="card-text"> {{ current_user.email }} </h6>
                    <hr>
                    <h6>Quizes Coming up: </h6>
                </div>
            </div>
        </div>
        <div class="col">
            <div class="row">
                <div class="col">
                    {% for message in get_flashed_messages() %}
                        <div class="alert alert-warning show fade" role="alert">
                            {{ message }}
                        </div>
                    {% endfor %}
                    <form action="{{ url_for('examiner.addquiz') }}" method="post">
                        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                        <div class="form-group">
                            <label for="New Quiz"></label>
                            <input class="form-control" type="text" id="newquiz" name="quizname" placeholder="Quiz Name">
                        </div>
                        <div class="form-group">
                            <label for="quizdate">Day</label>
                            <input class="form-control" type="date" name="quizdate" id="quizdate">
                        </div>
                        <div class="form-group">
                            <label for="quiztime">Time</label>
                            <input class="form-control" type="time" name="quiztime" id="quiztime">
                        </div>
                        <button type="submit" class="btn btn-outline-light">Add New Quiz</button>
                    </form>
                </div>
                <div class="col"></div>
            </div>
        </div>
    </div>
{% endblock %}

app/templates/examiner/quiz_n.html
{% extends "base.html" %}

{% block title %} Quizer - Register {% endblock %} 

{% block head %}
    {{ super() }}
{% endblock %}



{% block navbar %}
    <div class="container">
        {{ super() }}
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a href="{{ url_for('examiner.examinerhome') }}" class="nav-link">Home</a>
                </li>
                <li class="nav-item">
                    <a href="{{ url_for('examiner.quizlist') }}" class="nav-link">Quizes</a>
                </li>
            </ul>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="container text-light">
        {{ super() }}
        <div class="row">
            <div class="col">
                <div class="row">
                    <div class="col">
                        <div class="page-header"><h2>{{ quiz.name }}</h2></div>
                        <div class="questions d-flex flex-column justify-content-center align-items-center">
                            {% for page in pagination.items %}
                                <div data-toggle="list"
                                            class="list-group-item list-group-item-action text-light"
                                            style="background-color: #495158;">
                                    <div class="d-flex w-100 justify-content-between">
                                        <h5 class="mb-1">{{ page.detail }}</h5>
                                    </div>
                                    <p class="mb-1">{{ page.option1 }}</p>
                                    <p class="mb-1">{{ page.option2 }}</p>
                                    <p class="mb-1">{{ page.option3 }}</p>
                                    <p class="mb-1">{{ page.option4 }}</p>
                                    <p class="mb-1">Solution: {{ page.correct_option }}</p> 
                                    <hr>                                
                                </div>
                                <nav class="mt-3">
                                    <ul class="pagination" style="background-color: #495158;">
                                        {% for page in pagination.iter_pages() %}
                                            {% if page %}
                                                <li 
                                                class="page-item"><a href="{{ url_for('.onequiz', id=quiz.id, qid=page)}}" class="page-link">{{ page }}</a></li>
                                            {% else %}
                                                ...
                                            {% endif %}
                                        {% endfor %}
                                    </ul>   
                                </nav>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="col">
                        <h2 class="page-header">Add Question</h2>
                        {% for message in get_flashed_messages() %}
                            <div class="alert alert-warning show fade" role="alert">
                                {{ message }}
                            </div>
                        {% endfor %}

                        {% if form.errors %}
                            <div class="alert alert-warning show fade" role="alert">
                                {{ form.errors}}}
                            </div>
                        {% endif %}
                        <form id="form-addquestion" action="{{ url_for('examiner.addquestion', quiz_id=quiz.id) }}" method="post">
                            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                            <div class="form-group">
                                {{ form.detail(class_="form-control", id="questionfield", placeholder="Question") }}
                            </div>
                            <div class="form-group">
                                <div class="form-row">
                                    <div class="col">
                                        {{ form.option1(class_="form-control", id="option1field", placeholder="Option 1") }}
                                    </div>
                                    <div class="col">
                                        {{ form.option2(class_="form-control", id="option2field", placeholder="Option 2") }}
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="form-row">
                                    <div class="col">
                                        {{ form.option3(class_="form-control", id="option3field", placeholder="Option 3") }}
                                    </div>
                                    <div class="col">
                                        {{ form.option4(class_="form-control", id="option4field", placeholder="Option 4") }}
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                {{ form.correct_option(class_="form-control", placeholder="Solution") }}
                            </div>
                            <div class="form-group">
                                <!-- {{ form.submit(class_="btn btn-outline-light") }} -->
                                <button form="form-addquestion" class="btn btn-outline-light" type="submit">Add</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <hr>
        <div class="row">
            <div class="col">
                <form id="students" action="{{ url_for('examiner.registerstudents', id=quiz.id)}}" method="post">
                    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                    {% for student in students %}
                    <div class="form-group">
                        <div class="form-check">
                            <input class="form-check-input" type="checkbox" name="student" value="{{ student.id }}" id="defaultCheck1">
                            <label class="form-check-label" for="defaultCheck1">
                            {{ student.fname }} {{ student.lname }}
                            </label>
                        </div>
                    </div>
                    {% endfor %}
                    <button form="students" class="btn btn-outline-light" type="submit">Add Students</button>
                </form>
                
            </div>
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

app/templates/examiner/quizlist.html
{% extends "base.html" %}

{% block title %} Quizer - Register {% endblock %} 

{% block head %}
    {{ super() }}
{% endblock %}



{% block navbar %}
    <div class="container">
        {{ super() }}
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a href="{{ url_for('examiner.examinerhome') }}" class="nav-link">Home</a>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link">Quizes</a>
                </li>
            </ul>
        </div>
    </div>
{% endblock %}

{% block content %}
    {{ super() }}
    <div class="row">
        <div class="col">
                <div class="list-group" >
                    {% for quiz in quizes %}
                        <div style="background-color: #495158;" class="list-group-item text-light">
                            <div class="d-flex w-100 justify-content-between">
                                <h5 class="mb-1">{{ quiz.name }}</h5>
                                <small>3 days ago</small>
                            </div>
                            <hr>
                            <div>
                                <form action="{{ url_for('examiner.onequiz', id=quiz.id, qid=1) }}" method="get">
                                    <button type="submit" class="btn btn-outline-light">Go To Quiz</button>
                                </form>
                            </div>
                        </div>  
                    {% endfor %}
                </div>
        </div>
        <div class="col"></div>
    </div>
{% endblock %}